# Project meta
group = com.github.Antritus
version = 1.0.0
description = Entity glowing effect manipulation library to make entities glow globally or per player basis

# Gradle configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
 
